<?php
/**
 * About Page - Foundation 5 Project Template Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-7 columns">
        {I Profile I}
    </div>
    <div class="large-5 columns">
        {I Gallery I}
    </div>
</div>
